### ISSUE TITLE
yaml setting & .gitignore

### ISSUE THREAD

**Issue by morris821028** [JudgeGirl/JudgeNode#7]
建造 _config.yml 檔案，使用 YAML format 方便處理預設內容，而不直接去更動 source code。

```
# JUDGE_PATH/submission /testdata /source
# JUDGE_PATH: c:/Users/morris821028/Desktop/github/
JUDGE_PATH: /home/c2014/judgesister/

# MODE: limits user open previous source code & submit problem which not in contest.
CONTEST:
    MODE: true
    SUBMIT_LIMIT: 15

# DATABASE Setting, MySQL
DATABASE:
    host: '140.112.xxx.xxxx'
    user: 'c2015'
    password: 'xxxxxxxxxx'
    port: '3306'
    dbname: 'c2015'
```

加入 .gitignore 把 log 檔案移除。
